### ISSUE TITLE
Wireframe post.html

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/girlcode-2019-term1#27]
**This task is time-boxed. Do not spend longer than 15 minutes working on it!**

It's time to put some thought into what our post.html page looks like.

On paper, draw up a wireframe of post.html.

Remember to include all the different inputs we take:
- An image URL
- Message text
- An author
- ...more?

**Comment by michellechang-nz** [comment]
[Post html.pdf](https://github.com/girlcodeakl/girlcode-2019-term1/files/2991076/Post.html.pdf)
