### ISSUE TITLE
Emoji likes on posts - part 1

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/girlcode-2019-term1#35]
We're going to add some different like counters to our posts so people can vote on them in *feed.html*.

Open *feed.html* and find the function *displayMessage*.

Look at the code in the function that creates postHTML. You need to add some new div tags into the HTML to contain an emoji button (We'll start with one for now, but we can add more later).
- [x]  Do that!

You should now see the emoji button appear in the feed on every post.

We want the emoji to look clickable. Give it the css class `emojiButton` so you can style it. Then open up the css file and add some styles to make them look clickable.

In your css file:
```css
.emojiButton {
  
}
```

Look at some other websites for ideas. (How about this GitHub page you're looking at right now?) How can you tell what you're supposed to click on?

Some ideas to try:
* the mouse pointer arrow turns into a pointing finger
* the HTML element changes color when you *hover* over it with your mouse
* sometimes, the text is underlined, or gets an underline when you hover
* sometimes, there is a border and background color so it looks like a button

- [x] the emoji looks clickable

## make the emoji button do something

Normally, we add an event listener to a single button. Here, there could be lots of different emoji buttons in the message feed. We're going to add a special event listener that works for all the buttons at the same time.

Add this code to your JavaScript in `feed.html`, somewhere that is not inside any other function. 
```
function messageListClick(e) {
  if (e.target.classList.contains("emojiButton")) {
    console.log("button clicked!")
  } else {
    console.log("something else was clicked")
  }
}

let messageList = document.querySelector(".message-list");
messageList.addEventListener("click", messageListClick);
```
- [x] add the code

This adds an event listener to the entire message list. Every time you click on anything inside the list, the function runs.

When the function runs, it checks if you clicked on something with the class `emojiButton`. If you did, we're going to do something. Otherwise we won't.

- [x] Open your developer tools to the Console page and try clicking on the button and other parts of the message feed.
- [x] test: clicking the emoji button should display 'button clicked!'

If it doesn't, make sure your buttons have the same class that the code is looking for.

- [x] test: clicking on any part of a post except the button should display 'something else was clicked'

**Comment by michellechang-nz** [comment]
Emoji has been added!
